name: CI

on:
  pull_request:
  push:
    branches: main

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macOS-latest]
        resolver:
        - nightly # ghc-9.4.5
        - lts-20  # ghc-9.2.7

    steps:
    - uses: actions/checkout@v3
    - uses: freckle/stack-cache-action@v2
      with:
        prefix: v1/
        stack-yaml: stack/stack-${{ matrix.resolver }}.yaml
    - uses: freckle/stack-action@v3
      with:
        stack-yaml: stack/stack-${{ matrix.resolver }}.yaml
        stack-arguments: --bench --no-run-benchmarks --haddock --no-haddock-deps
